[package]
name = "dps-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "dps_calculator"
path = "dps-calculator/src/lib.rs"

[[bin]]
name = "dps_calculator"
path = "main.rs"
